---
title: "Class-2019-11-07"
author: "Emily Axelsen"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(babynames) 
library(tidyverse)
```

```{r include=FALSE}
A <- babynames %>%
  distinct(year) %>%
  nrow()
```

There are `r A` years worth of baby names in this data set. 

```{r include=FALSE}
B <- babynames %>%
  distinct(name) %>%
  nrow()
```

There are `r B` unique baby names. 

```{r names that come up the most, include=FALSE}
babynames %>%
  group_by(name) %>%
  summarize(total = n()) %>%
  arrange(desc(total)) 

# 278 accounts for both male and female --> 134 Females and 134 males named francis, james...

```



```{r make sure there was a female James, include=FALSE}
babynames %>%
  filter(name == "James")

# see that there actually was a female named james 

```


```{r}
Emily <- babynames %>%
  filter(name == "Emily")

Emily %>%
  ggplot(aes(x = year, y = n)) +
  geom_col() + 
  labs(x = "Year",
       y = "Number of People Named Emily",
       title = "An Exploration of the Number of People Named Emily 1880 - 2017")
```




```{r include=FALSE}
babynames %>%
  filter(sex == "M") %>%
  count(name) %>%
  arrange(desc(n)) %>%
  filter(n == 138) %>%
  nrow()

# Another way to do this:

all_male_names <- babynames %>%
  filter(sex == "M")%>%
  group_by(name) %>%
  summarize(total = n()) %>%
  filter(total == 138) %>%
  pluck("name")

```



```{r include=FALSE}
one_name <- babynames %>%
  filter(name == "Brian", sex == "M")

lm.obj <- lm(data = one_name, prop ~ year)

# .000000724 (or something like that) - Brian gets more and more common for each year increase by .00000724

```


```{r include=FALSE}
babynames %>%
  filter(name %in% all_male_names) %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  nest() %>% # creating extra data set of data (list) 
  mutate(models = map(data, ~lm(prop ~ year, data = .x))) %>% # .x = grab each individual data types
  mutate(coeficients = map(models, ~ coef(.x))) %>%
  mutate(slope = map_dbl(coeficients, ~pluck(.x, "year"))) %>%
  arrange(desc(slope))

# coefficient = slope
```









